# Generated by Django 5.1.2 on 2025-03-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.AddField(
            model_name='message',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/'),
        ),
    ]
