# Generated by Django 5.1.2 on 2025-03-23 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_message_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='timestamp',
        ),
    ]
